name: CI

on:
  push:
    branches:
      - main
      - init-repo
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: true  # Initialize submodules

    - name: Set up C++ compiler
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake git

    - name: Update submodules recursively
      run: |
        git submodule update --init --recursive

    - name: Build project
      run: |
        mkdir build
        cd build
        cmake ..
        make

    - name: Run tests
      run: |
        cd build && ./mixed_storage_test
